version: '1'

services:
  server:
    build: server/
    ports: 
      - 8050:8050
    networks:
      - server-to-rabbit
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: node server.js
    volumes:
      - /server:/server

  highload-service:
    build: highloadservice/
    command: go run server.go
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbit-to-generator
    volumes:
      - /highloadservice:/highloadservice
  
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq
    ports:
    - 15672:15672
    - 5672:5672
    networks:
      - server-to-rabbit
      - rabbit-to-generator
    healthcheck:
      test: rabbitmq-diagnostics check_running || exit 1
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 10s

networks:
  server-to-rabbit:
    driver: bridge
  rabbit-to-generator:
    driver: bridge 